/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterDefault: typeof import('./components/layout/FooterDefault.vue')['default']
    HeaderDefault: typeof import('./components/layout/HeaderDefault.vue')['default']
    BaseIcon: typeof import('./components/ui/BaseIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
